language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.maven'

script: "./mvnw clean package"

# CI 실행 완료 시 메일로 알림
notifications:
  email:
    recipients:
      - harimlee1022@gmail.com